services:
  daily-diet:
    image: daily-diet:v11
    container_name: daily-diet
    volumes: 
      - db:/var/lib/sqlite
    ports:
      - 3000:3333
    env_file:
      - .env
    command: npm run start:prod
    
volumes:
  db: